#!/bin/sh

MOUNTPOINT=/tmp/pico

set -e # Exit on first error

mkdir -p ${MOUNTPOINT}
sudo mount -o uid=1000,gid=1000 /dev/disk/by-label/RPI-RP2 ${MOUNTPOINT}
elf2uf2-rs $1
cp $1.uf2 ${MOUNTPOINT}
sync
sudo umount ${MOUNTPOINT}

